version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/steinfletcher/github-org-clone

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS

      - restore_cache:
          keys:
            - v1-pkg-cache

      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: go get github.com/jstemmer/go-junit-report
      - run: dep ensure
      - run:
          name: Run unit tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            make test | tee ${TEST_RESULTS}/go-test.out
      - run: make

      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: circleci/golang:1.10.3
    working_directory: /go/src/github.com/steinfletcher/github-org-clone

    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2

  build_and_test:
    jobs:
    - build:
       branches:
         only: master
       tags:
         ignore: /.*/

  release:
    jobs:
    - build:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
    - release:
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore: /.*/
        requires:
          - build
